import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { ArrowDownToLine, Check, CheckCheck, ChevronDown, CircleAlert, CircleCheck, Clipboard, Clock3, Code2, Fingerprint, GitCompareArrows, ListFilter, LoaderCircle, LockKeyhole, Menu, Plus, Radio, Search, ShieldCheck, Unplug, Wallet, X } from 'lucide-react';
import { chain, connectWallet, ensureTestnet, intentSeal, publicClient, registryAbi, registryAddress, sealId } from '../chain';

type Run = { id: string; name: string; intent: Record<string, unknown>; observed: Record<string, unknown> | null; created: number; intentHash: `0x${string}`; state: 'intent' | 'verified' | 'mismatch'; txHash?: `0x${string}`; onchain?: boolean; submitter?: string; note?: string; sample?: boolean };
type Tab = 'runs' | 'seal' | 'verify';
type Provider = Awaited<ReturnType<typeof connectWallet>>['provider'];
const demoRuns: Run[] = [
  { id: 'run-7f31a', name: 'Treasury rebalance', intent: { action: 'swap', from: 'USDC', to: 'BOT', maxAmount: '250.00', chainId: 968, recipient: '0x7e2…13f2' }, observed: { action: 'swap', from: 'USDC', to: 'BOT', amount: '248.50', chainId: 968, recipient: '0x7e2…13f2' }, created: Date.now() - 1180000, intentHash: `0x${'a6f210d4c8304a22'.repeat(4)}`, state: 'verified', note: 'Sample data · local only', sample: true },
  { id: 'run-48cd2', name: 'Vendor payout', intent: { action: 'transfer', asset: 'USDC', maxAmount: '80.00', chainId: 968, recipient: '0x91b…4dc0' }, observed: { action: 'transfer', asset: 'USDC', amount: '80.00', chainId: 56, recipient: '0x91b…4dc0' }, created: Date.now() - 4060000, intentHash: `0x${'8dc0b624f5a94710'.repeat(4)}`, state: 'mismatch', note: 'Sample data · local only', sample: true },
  { id: 'run-d3e09', name: 'Policy check · API spend', intent: { action: 'api_call', service: 'weather-data', maxCost: '0.04 BOT', chainId: 968 }, observed: null, created: Date.now() - 9370000, intentHash: `0x${'09cc2e71bd654fa3'.repeat(4)}`, state: 'intent', note: 'Sample data · local only', sample: true }
];
const pretty = (v: unknown) => JSON.stringify(v, null, 2);
const short = (s?: string) => s ? `${s.slice(0, 10)}…${s.slice(-6)}` : '—';
const time = (n: number) => new Intl.DateTimeFormat(undefined, { hour: '2-digit', minute: '2-digit' }).format(n);
const loadRuns = (key: string): Run[] => { try { const parsed = JSON.parse(localStorage.getItem(key) || 'null'); return Array.isArray(parsed) ? parsed : demoRuns; } catch { return demoRuns; } };

export default function App() {
  const [account, setAccount] = useState('');
  const [chainId, setChainId] = useState<number | null>(null);
  const [tab, setTab] = useState<Tab>((location.hash.replace('#', '') as Tab) || 'runs');
  const [runs, setRuns] = useState<Run[]>([]);
  const [loadedKey, setLoadedKey] = useState('');
  const [selected, setSelected] = useState('');
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [mobileDetail, setMobileDetail] = useState(false);
  const [toast, setToast] = useState('');
  const [walletBusy, setWalletBusy] = useState(false);
  const [rpcState, setRpcState] = useState<'loading' | 'ready' | 'error'>('loading');
  const [head, setHead] = useState<bigint | null>(null);
  const [codePresent, setCodePresent] = useState<boolean | null>(null);
  const [intentText, setIntentText] = useState(`{
  "action": "transfer",
  "asset": "USDC",
  "maxAmount": "25.00",
  "chainId": 968,
  "recipient": "0x..."
}`);
  const [runName, setRunName] = useState('New run');
  const [observedText, setObservedText] = useState('');
  const [pending, setPending] = useState(false);
  const [txStage, setTxStage] = useState('');
  const providerRef = useRef<Provider | null>(null);
  const accountsHandler = useRef<((...args: unknown[]) => void) | null>(null);
  const chainHandler = useRef<((...args: unknown[]) => void) | null>(null);
  const storeKey = `runseal:v1:${chain.id}:${registryAddress.toLowerCase()}:${account.toLowerCase() || 'local'}`;

  useEffect(() => { const initial = loadRuns(storeKey); setRuns(initial); setSelected(new URLSearchParams(location.search).get('run') || initial[0]?.id || ''); setLoadedKey(storeKey); }, [storeKey]);
  useEffect(() => { if (loadedKey === storeKey) localStorage.setItem(storeKey, JSON.stringify(runs)); }, [runs, storeKey, loadedKey]);
  useEffect(() => { const onHash = () => setTab((location.hash.replace('#', '') as Tab) || 'runs'); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => {
    let live = true;
    const refresh = async () => { try { const [id, block, code] = await Promise.all([publicClient.getChainId(), publicClient.getBlockNumber(), registryAddress ? publicClient.getBytecode({ address: registryAddress }) : Promise.resolve(undefined)]); if (!live) return; setChainId(id); setHead(block); setCodePresent(code ? code !== '0x' : null); setRpcState(id === chain.id ? 'ready' : 'error'); } catch { if (live) setRpcState('error'); } };
    void refresh(); const timer = window.setInterval(refresh, 25000); return () => { live = false; clearInterval(timer); };
  }, []);
  const selectedRun = runs.find(r => r.id === selected) || null;
  const shown = useMemo(() => runs.filter(r => `${r.name} ${r.id} ${r.intent.action || ''}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || r.state === filter)), [runs, search, filter]);
  const notice = useCallback((message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3600); }, []);
  const navigate = (next: Tab) => { location.hash = next; setTab(next); setMobileDetail(false); document.querySelector('.tabs')?.classList.remove('open'); };
  const choose = (run: Run) => { setSelected(run.id); const u = new URL(location.href); u.searchParams.set('run', run.id); history.replaceState(null, '', u); setMobileDetail(true); };
  const connect = async () => { setWalletBusy(true); try { const w = await connectWallet(); setAccount(w.account); const id = await w.wallet.getChainId(); setChainId(id); notice(id === chain.id ? 'Wallet connected on BOT Chain Testnet' : 'Wallet connected · switch to BOT Chain Testnet to write'); if (providerRef.current) { if (accountsHandler.current) providerRef.current.removeListener?.('accountsChanged', accountsHandler.current); if (chainHandler.current) providerRef.current.removeListener?.('chainChanged', chainHandler.current); } providerRef.current = w.provider; accountsHandler.current = (...args) => { const xs = args[0]; const next = Array.isArray(xs) ? String(xs[0] || '') : ''; setAccount(next); setSelected(''); }; chainHandler.current = (...args) => { setChainId(Number.parseInt(String(args[0]), 16)); setSelected(''); }; w.provider.on?.('accountsChanged', accountsHandler.current); w.provider.on?.('chainChanged', chainHandler.current); } catch (e) { notice(e instanceof Error ? e.message : 'Wallet connection failed'); } finally { setWalletBusy(false); } };
  const disconnect = () => { if (providerRef.current) { if (accountsHandler.current) providerRef.current.removeListener?.('accountsChanged', accountsHandler.current); if (chainHandler.current) providerRef.current.removeListener?.('chainChanged', chainHandler.current); } providerRef.current=null; accountsHandler.current=null; chainHandler.current=null; setAccount(''); setSelected(''); notice('Disconnected in Runseal. Wallet permissions may remain enabled in the wallet.'); };
  const createRun = (event: FormEvent) => { event.preventDefault(); try { if (intentText.length > 24000) throw new Error('Intent must be under 24 KB.'); const intent = JSON.parse(intentText); if (!intent || Array.isArray(intent) || typeof intent !== 'object') throw new Error('Intent must be a JSON object.'); const run: Run = { id: `run-${crypto.randomUUID().slice(0, 8)}`, name: runName.trim() || 'Untitled run', intent, observed: null, created: Date.now(), intentHash: intentSeal(intent), state: 'intent' }; setRuns(prev => [run, ...prev]); setSelected(run.id); navigate('runs'); setMobileDetail(true); notice('Intent fingerprinted locally. No transaction was sent.'); } catch (e) { notice(e instanceof Error ? e.message : 'Invalid JSON intent'); } };
  const verifyObservation = (event: FormEvent) => { event.preventDefault(); if (!selectedRun) return; try { if (observedText.length > 24000) throw new Error('Observation must be under 24 KB.'); const observed = JSON.parse(observedText); if (!observed || Array.isArray(observed) || typeof observed !== 'object') throw new Error('Observation must be a JSON object.'); const matches = Object.entries(selectedRun.intent).every(([key, value]) => observed[key] === value || (key === 'maxAmount' && typeof observed.amount === 'string' && Number(observed.amount) <= Number(String(value)))); const next = { ...selectedRun, observed, state: (matches ? 'verified' : 'mismatch') as Run['state'] }; setRuns(prev => prev.map(r => r.id === next.id ? next : r)); setObservedText(''); notice(matches ? 'Local comparison passed. This does not prove execution.' : 'Mismatch found. Inspect the differing fields below.'); } catch (e) { notice(e instanceof Error ? e.message : 'Invalid observation JSON'); } };
  const sealOnchain = async (run: Run) => {
    if (run.sample) { notice('Sample runs are illustrative. Create a new intent before using the registry.'); return; }
    if (!registryAddress || !/^0x[a-fA-F0-9]{40}$/.test(registryAddress)) { notice('Set VITE_RUNSEAL_CONTRACT_ADDRESS to use the registry.'); return; }
    setPending(true); setTxStage('Connecting wallet');
    try {
      const w = await connectWallet(); setAccount(w.account); await ensureTestnet(w.provider); setChainId(chain.id);
      setTxStage('Checking deployed registry'); const code = await publicClient.getBytecode({ address: registryAddress }); if (!code || code === '0x') throw new Error('No contract bytecode at configured address. Check the deployment address.');
      const id = sealId(run.id); const hash = run.intentHash;
      setTxStage('Simulating sealIntent'); const simulation = await publicClient.simulateContract({ address: registryAddress, abi: registryAbi, functionName: 'sealIntent', args: [id, hash], account: w.account });
      setTxStage('Confirm in wallet'); const tx = await w.wallet.writeContract(simulation.request); setTxStage('Waiting for confirmation'); const receipt = await publicClient.waitForTransactionReceipt({ hash: tx }); if (receipt.status !== 'success') throw new Error('Transaction reverted. No registry seal confirmed.');
      setTxStage('Reading registry state'); const record = await publicClient.readContract({ address: registryAddress, abi: registryAbi, functionName: 'seals', args: [id] }); if (record[1].toLowerCase() !== hash.toLowerCase()) throw new Error('Transaction confirmed, but registry read-back did not match the intended commitment.');
      setRuns(prev => prev.map(r => r.id === run.id ? { ...r, onchain: true, txHash: tx, submitter: record[0] } : r)); notice('Registry seal confirmed and read back. It commits a hash only; it does not prove the action happened.');
    } catch (e) { const message = e instanceof Error ? e.message : 'Registry write failed'; notice(message.includes('User rejected') ? 'Wallet request rejected. No seal confirmed.' : message); } finally { setPending(false); setTxStage(''); }
  };
  const exportRuns = () => { const blob = new Blob([JSON.stringify(runs, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'runseal-runs.json'; a.click(); URL.revokeObjectURL(a.href); };
  const copy = async (text: string) => { try { await navigator.clipboard.writeText(text); notice('Copied to clipboard'); } catch { notice('Clipboard unavailable'); } };
  const statusLabel = (r: Run) => r.onchain ? 'Registry confirmed' : r.state === 'verified' ? 'Local match' : r.state === 'mismatch' ? 'Mismatch' : 'Intent only';

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#runs" onClick={() => navigate('runs')}><img src="/seal.svg" alt=""/><span>runseal</span></a><nav className="tabs" aria-label="Main workflows">{([['runs','Runs'],['seal','Seal intent'],['verify','Verify']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>navigate(id)}>{label}</button>)}</nav><div className="top-actions"><div className={`network ${rpcState}`} title={rpcState==='ready'?`BOT Chain Testnet · block ${head}`:'BOT Chain RPC status'}><span className="network-dot"/>{rpcState==='loading'?'Connecting':rpcState==='ready'?'BOT Testnet':'RPC unavailable'}{chainId!==null&&chainId!==chain.id?' · switch wallet':''}</div>{account?<button className="wallet-btn connected" onClick={disconnect} title="Disconnect this interface"><Wallet size={15}/><span>{short(account)}</span><Unplug size={14}/></button>:<button className="wallet-btn" onClick={connect} disabled={walletBusy}>{walletBusy?<LoaderCircle className="spin" size={15}/>:<Wallet size={15}/>}<span>{walletBusy?'Connecting':'Connect wallet'}</span></button>}<button className="icon-btn mobile-menu" aria-label="Open workflow menu" onClick={()=>document.querySelector('.tabs')?.classList.toggle('open')}><Menu size={19}/></button></div></header>
    <main className={`workspace ${mobileDetail?'mobile-detail':''} ${tab!=='runs'?'mobile-form':''}`}>
      <aside className="run-rail"><div className="rail-head"><div><h1>Runs</h1><p>Intent before outcome.</p></div><button className="icon-btn" title="Create a new run" aria-label="Create run" onClick={()=>navigate('seal')}><Plus size={18}/></button></div><label className="search"><Search size={15}/><input aria-label="Search runs" placeholder="Find a run…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd></label><div className="rail-tools"><span>{shown.length} runs</span><label className="filter"><ListFilter size={14}/><select aria-label="Filter runs" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All states</option><option value="intent">Intent only</option><option value="verified">Local match</option><option value="mismatch">Mismatch</option></select></label></div><div className="run-list">{shown.map(r=><button key={r.id} className={`run-row ${selected===r.id?'selected':''}`} onClick={()=>choose(r)}><span className={`run-mark ${r.state}`}>{r.state==='mismatch'?<CircleAlert size={15}/>:r.state==='verified'?<Check size={15}/>:<Clock3 size={15}/>}</span><span className="run-copy"><strong>{r.name}</strong><small>{r.id} · {time(r.created)}</small></span><span className="row-chevron">›</span></button>)}{!shown.length&&<div className="empty-list"><Fingerprint size={24}/><strong>No runs found</strong><span>Try another search or create an intent.</span></div>}</div><button className="export-btn" onClick={exportRuns}><ArrowDownToLine size={15}/> Export runs</button><div className="rail-foot"><span className="sample-dot"/> Examples are local sample data</div></aside>
      <section className="content">
        {tab==='seal'&&<section className="form-page"><button className="back-link" onClick={()=>navigate('runs')}>← Back to runs</button><h2>Seal an intent</h2><p className="lede">Set the expected action before execution. Runseal fingerprints your JSON locally; it does not run an agent.</p><form onSubmit={createRun} className="intent-form"><label>Run name<input value={runName} onChange={e=>setRunName(e.target.value)} maxLength={90} required/></label><label>Expected intent <span className="field-note">JSON object · up to 24 KB</span><textarea spellCheck={false} value={intentText} onChange={e=>setIntentText(e.target.value)} rows={13} required/></label><div className="fingerprint-preview"><Fingerprint size={18}/><span>Local commitment</span><code>{intentSeal(safeJson(intentText))}</code></div><button className="primary-btn" type="submit"><LockKeyhole size={16}/> Create local intent</button><p className="form-disclaimer">No wallet prompt or transaction occurs here. Registry sealing is a separate, explicit action from a run’s detail view.</p></form></section>}
        {tab==='verify'&&<section className="form-page"><h2>Verify an observation</h2><p className="lede">Compare a supplied outcome against an intent. This is a local field check—not proof of execution, oracle attestation, or business truth.</p>{!selectedRun?<div className="empty-state"><Fingerprint/><strong>Select a run first</strong><span>Choose a run in the left pane, then return here to compare an observation.</span><button className="secondary-btn" onClick={()=>navigate('runs')}>Choose a run</button></div>:<form className="intent-form" onSubmit={verifyObservation}><div className="target-run"><span>Comparing against</span><strong>{selectedRun.name}</strong><code>{selectedRun.id}</code></div><label>Observed result <span className="field-note">Paste the values you want to compare</span><textarea spellCheck={false} placeholder={'{\n  "action": "transfer",\n  "asset": "USDC",\n  "amount": "24.00",\n  "chainId": 968\n}'} value={observedText} onChange={e=>setObservedText(e.target.value)} rows={12} required/></label><button className="primary-btn" type="submit"><GitCompareArrows size={16}/> Compare fields</button></form>}</section>}
        {tab==='runs'&&(!selectedRun?<div className="empty-state first-empty"><img src="/seal.svg" alt=""/><h2>Start with the intent.</h2><p>Write down what an agent is allowed to do. Compare the observed outcome against that commitment before accepting it.</p><button className="primary-btn" onClick={()=>navigate('seal')}><Plus size={16}/> Seal an intent</button><span>Sample runs are marked local; no production activity is shown.</span></div>:<RunDetail run={selectedRun} account={account} onSeal={()=>sealOnchain(selectedRun)} pending={pending} txStage={txStage} onVerify={()=>navigate('verify')} onCopy={copy} onBack={()=>setMobileDetail(false)} statusLabel={statusLabel(selectedRun)} codePresent={codePresent} rpcState={rpcState}/>) }
        {tab==='runs'&&<footer className="content-foot"><span><Radio size={13}/> Read-only public chain status</span><span>Chain 968 · {head===null?'—':`Block ${head.toString()}`}</span><span>{registryAddress?codePresent===true?'Registry code found':codePresent===false?'No code at address':'Checking registry':'Set contract address to enable registry reads'}</span></footer>}
      </section>
    </main>
    {pending&&<div className="tx-banner" role="status"><LoaderCircle className="spin" size={16}/><span>{txStage || 'Registry transaction in progress'}</span><span>Confirm only if the wallet request matches this intent.</span></div>}
    {toast&&<div className="toast" role="status"><CircleCheck size={16}/>{toast}<button aria-label="Dismiss" onClick={()=>setToast('')}><X size={15}/></button></div>}
    <div className="sr-only" aria-live="polite">{rpcState==='ready'?`Connected to ${chain.name}`:'Chain read unavailable'}</div>
  </div>;
}

function safeJson(text: string) { try { return JSON.parse(text); } catch { return {}; } }

function RunDetail({ run, account, onSeal, pending, txStage, onVerify, onCopy, onBack, statusLabel, codePresent, rpcState }: { run: Run; account: string; onSeal:()=>void; pending:boolean; txStage:string; onVerify:()=>void; onCopy:(s:string)=>void; onBack:()=>void; statusLabel:string; codePresent:boolean|null; rpcState:string }) {
  const expected = run.intent; const observed = run.observed;
  const keys = [...new Set([...Object.keys(expected), ...Object.keys(observed || {})])];
  const diff = (key:string) => observed && Object.hasOwn(expected,key) && Object.hasOwn(observed,key) && JSON.stringify(expected[key])!==JSON.stringify(observed[key]) && !(key==='maxAmount'&&Number(String(observed.amount))<=Number(String(expected.maxAmount)));
  return <article className="detail"><div className="detail-head"><button className="back-mobile" onClick={onBack}>← Runs</button><div><div className="title-line"><h2>{run.name}</h2><span className={`state-pill ${run.onchain?'confirmed':run.state}`}>{run.onchain?<CheckCheck size={13}/>:run.state==='mismatch'?<CircleAlert size={13}/>:run.state==='verified'?<Check size={13}/>:<Clock3 size={13}/>} {statusLabel}</span></div><div className="metadata"><code>{run.id}</code><span>·</span><span>{new Date(run.created).toLocaleString()}</span><span>·</span><span>{run.note || (run.onchain?'BOT Chain Testnet registry':'Local record')}</span></div></div><button className="icon-btn" title="Copy run ID" aria-label="Copy run ID" onClick={()=>onCopy(run.id)}><Clipboard size={16}/></button></div>
    <section className="progression" aria-label="Execution evidence stages"><Stage n="01" title="Intent" desc="Expected fields" state="done"/><div className="stage-line"/><Stage n="02" title="Sealed" desc={run.onchain?'Registry read-back':'Local fingerprint'} state={run.onchain?'chain':'done'}/><div className="stage-line"/><Stage n="03" title="Observed" desc={observed?'Supplied result':'Not supplied'} state={observed?'done':'quiet'}/><div className="stage-line"/><Stage n="04" title="Verified" desc={run.state==='mismatch'?'Fields differ':run.state==='verified'?'Local comparison':'Not checked'} state={run.state==='mismatch'?'bad':run.state==='verified'?'done':'quiet'}/></section>
    <div className="detail-toolbar"><div><span className="section-title">Intent ↔ observation</span><span className="subtle">{observed?'Field-by-field comparison':'Waiting for observed fields'}</span></div><button className="secondary-btn" onClick={onVerify}><GitCompareArrows size={15}/>{observed?'Compare again':'Add observation'}</button></div>
    <div className="compare"><div className="compare-head"><span>FIELD</span><span>EXPECTED</span><span>OBSERVED</span><span>CHECK</span></div>{keys.map(k=><div className={`compare-row ${diff(k)?'mismatch':''}`} key={k}><strong>{k}</strong><code>{expected[k]===undefined?'—':String(expected[k])}</code><code>{!observed||observed[k]===undefined?(k==='maxAmount'&&observed?.amount?String(observed.amount):'—'):String(observed[k])}</code><span className={`check-state ${observed?(diff(k)?'bad':'ok'):'wait'}`}>{observed?(diff(k)?'Different':'Match'):'Pending'}</span></div>)}{observed&&run.state==='verified'&&<div className="compare-note"><Check size={14}/>All required expected fields match locally. This comparison is not an attestation that the action occurred.</div>}{observed&&run.state==='mismatch'&&<div className="compare-note bad-note"><CircleAlert size={14}/>One or more supplied values differ. Confirm the result source and policy before accepting it.</div>}</div>
    <section className="seal-section"><div className="seal-top"><div><span className="section-title">Commitment</span><p>The fingerprint binds the intent JSON. It does not guarantee the agent followed it.</p></div><button className="icon-btn" title="Copy commitment" aria-label="Copy commitment" onClick={()=>onCopy(run.intentHash)}><Clipboard size={15}/></button></div><div className="hash-box"><img src="/seal.svg" alt=""/><code>{run.intentHash}</code><span>KECCAK-256 · LOCAL</span></div>{run.onchain?<div className="chain-receipt"><span className="ok-symbol"><CheckCheck size={16}/></span><div><strong>Commitment read back from registry</strong><small>Submitter {short(run.submitter)} · the contract stores the seal only.</small></div><a href={`${chain.blockExplorers.default.url}/tx/${run.txHash}`} target="_blank" rel="noreferrer">View transaction ↗</a></div>:<div className="seal-action"><div><strong>{run.sample?'Illustrative sample':account?'Ready for explicit wallet approval':'Wallet not connected'}</strong><small>{run.sample?'Sample fingerprints are not derived from their displayed JSON and cannot be anchored.':codePresent===false?'No deployed code detected at configured address.':rpcState!=='ready'?'BOT Chain read unavailable.':account?'Simulation runs before wallet confirmation.':'Connect a wallet to submit a registry commitment.'}</small></div><button className="primary-btn" disabled={run.sample||pending||!account||codePresent!==true||rpcState!=='ready'} onClick={onSeal}>{pending?<><LoaderCircle className="spin" size={15}/>{txStage||'Working'}</>:<><LockKeyhole size={15}/> Seal in registry</>}</button></div>}</section>
    <details className="raw-details"><summary><Code2 size={15}/> Raw intent JSON <ChevronDown size={14}/></summary><pre>{pretty(run.intent)}</pre></details>
    <div className="honesty-note"><ShieldCheck size={15}/><span><strong>What this proves:</strong> if registry-confirmed, this wallet submitted a commitment hash and the registry returned the same stored hash. It does not prove the agent executed the intent or that the observed data is truthful.</span></div>
  </article>;
}
function Stage({n,title,desc,state}:{n:string;title:string;desc:string;state:string}) { return <div className={`stage ${state}`}><span className="stage-num">{state==='done'||state==='chain'?<Check size={14}/>:state==='bad'?<CircleAlert size={14}/>:n}</span><div><strong>{title}</strong><small>{desc}</small></div></div>; }
